---
title: "Les joueurs"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float: yes
---

## **Liste des joueurs**

```{r, formaterTableau, echo = FALSE, fig.align='center',message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# Fonction pour formatter les tableaux
library(DT)
library(dplyr)
formaterTableau<-function(tab){
  datatable(tab, 
            rownames = F, 
            width="100%",
            extensions = c('Buttons','ColReorder','FixedColumns')
            ,options = list(
              dom = 'Blfrtip',
              buttons = c("colvis",'csv', 'excel', 'pdf'),
              colReorder = TRUE,
              lengthMenu = list(c(5, 25,50, -1), c('5', '25',"50", 'Tout')),
              pageLength = 10
            )
   )
}

formaterTableauSimple<-function(tab){
  datatable(tab, 
            rownames = F, 
            width="100%",
            extensions = c('Buttons','ColReorder','FixedColumns')
            ,options = list(
              dom = 'Blfrtip',
              lengthMenu = list(c(5, 25,50, -1), c('5', '25',"50", 'Tout')),
              pageLength = 10
            )
   )
}
```



```{r listeJoueurs, echo=FALSE, fig.align='center', message=FALSE, warning=FALSE, paged.print=FALSE}
# Fonction pour formatter les tableaux
library(DT)
library(dplyr)

listeJoueurs <- rio::import("1_joueurs/licencies 2020.txt") %>% 
  mutate(Nom=paste0(substr(Nom,1,1),"."),
         Genre=forcats::fct_recode(Sexe,Masculin="M", Feminin="F"),
         `Type de licence`=forcats::fct_recode(Type, `Tradi (compétition)`="T", `Promo (entrainement)`="P"),
         `Catégorie`= paste0(`Categ Sp.`, " ans"),
         `Classement`=paste0("Classé·e ",Clast),
         `Date de naissance`=Naissance,
         `Pts (début saison)`=Points) %>% 
  select("N° Licence","Genre","Prénom","Nom","Date de naissance","Type de licence","Catégorie","Classement","Pts (début saison)") %>% 
  arrange(desc(`Type de licence`),`Prénom`) 

formaterTableau(listeJoueurs)
```

---

## **Répartition des joueurs**

### - Par genre
```{r, parGenre, echo = FALSE, fig.align='center'}
as.data.frame(listeJoueurs %>% count(Genre, sort = TRUE)) %>% rename(Nombre=n) %>%  formaterTableauSimple()

```

### - Par catégorie

```{r, parCategorie, echo = FALSE, fig.align='center'}
library(forcats)

as.data.frame(listeJoueurs %>% count(`Catégorie`, sort = TRUE)) %>% rename(Nombre=n) %>% formaterTableauSimple()

```

### - Par Classement
```{r, parClassement, echo = FALSE, fig.align='center'}
as.data.frame(listeJoueurs %>% count(Classement, sort = TRUE)) %>% rename(Nombre=n) %>%formaterTableauSimple()
```

### - Par type de licence

```{r,parTypeLicence, echo = FALSE, fig.align='center'}
as.data.frame(listeJoueurs %>% count(`Type de licence`, sort = TRUE)) %>% rename(Nombre=n) %>%formaterTableauSimple()
```

## **Statistiques**

```{r, echo = FALSE, fig.align='center'}
library(tidyverse)
cool_function <- function(x, alpha) return(sin(alpha*x))
xs <- seq(0, pi*1.5, 0.005)
ys <- cool_function(xs, 1)
results <- data_frame(xs, ys, alpha = "1")
for(alpha in seq(0,3, 0.1)){
  results <- results %>% 
    bind_rows(data_frame(
      xs, 
      ys = cool_function(xs, alpha),
      alpha = as.character(alpha)
    ))
}

ggplot(results, aes(x = xs, y = ys, color = alpha)) + 
  geom_line() + 
  theme_bw() + 
  theme(legend.position="none")
```

---

### **Evolution des joueurs**, depuis 2005

<span style="background-color:orange"> ** ------------------------------- PARTIE EN COURS DE DEVELOPPEMENT ------------------------------- ** </span>


```{r, echo = FALSE, fig.align='center'}
library(billboarder)
evolutionJoueurs <- read.csv2("1_joueurs/evolutionJoueurs.csv")
billboarder() %>% 
  bb_linechart(
    data = evolutionJoueurs, 
    type = "spline"
  ) %>% 
  bb_x_axis(tick = list(format = "%Y-%m", fit = FALSE)) %>% 
  bb_x_grid(show = TRUE) %>% 
  bb_y_grid(show = TRUE) %>% 
  bb_colors_manual("consommation" = "firebrick", "production" = "forestgreen") %>% 
  bb_legend(position = "right") %>% 
  bb_zoom(
    enabled = list(type = "drag"),
    resetButton = list(text = "Annuler le Zoom")
  ) %>% 
  bb_labs(title = "Evolution annuelle des joueurs",
          y = "Points",
          caption = "Données FFTT")

```

<span style="background-color:orange"> ** ------------------------------- PARTIE EN COURS DE DEVELOPPEMENT ------------------------------- ** </span>


